#!/bin/sh
PATH=/bin:/sbin:/usr/bin:/usr/sbin; export PATH

# ----------------------------------------
# unload before install
for f in /Library/LaunchDaemons/org.pqrs.PCKeyboardHack.* /Library/LaunchAgents/org.pqrs.PCKeyboardHack.*; do
    [ -f $f ] && launchctl unload $f 2> /dev/null
done

startup="/Applications/PCKeyboardHack/scripts/startup.sh"
[ -f "$startup" ] && "$startup" stop

startup="/Library/org.pqrs/PCKeyboardHack/scripts/startup.sh"
[ -f "$startup" ] && "$startup" stop

# ----------------------------------------
# uninstall
rm -rf /Applications/PCKeyboardHack
rm -rf /Library/org.pqrs/PCKeyboardHack

rm -rf /Library/PreferencePanes/PCKeyboardHack.prefPane

rm -f /Library/LaunchDaemons/org.pqrs.PCKeyboardHack.*
rm -f /Library/LaunchAgents/org.pqrs.PCKeyboardHack.*

# Don't remove uninstaller because
# this script is also called from uninstaller and
# we need to keep PCKeyboardHackUninstaller.icns while uninstaller is running.
# rm -rf /tmp/PCKeyboardHack_uninstaller.*

exit 0
