all:
	$(MAKE) -C ../../../pkginfo
	$(MAKE) -C ../../bridge/generator/bridge_version
	$(MAKE) -C ../../bridge/generator/config
	$(MAKE) -C 10.8
	$(MAKE) -C 10.9

clean:
	$(MAKE) -C 10.8 clean
	$(MAKE) -C 10.9 clean
