#!/bin/sh
PATH=/bin:/sbin:/usr/bin:/usr/sbin; export PATH

# ------------------------------------------------------------
# set file permissions
for f in \
    '/Applications/Seil.app' \
    '/Library/Application Support/org.pqrs/Seil' \
    '/Library/LaunchDaemons/org.pqrs.Seil.load.plist' \
    ; do
    echo "set file permissions: $f"
    sh '/Library/Application Support/org.pqrs/Seil/setpermissions.sh' "$f"
    chown -Rh root:wheel "$f"
done

# ------------------------------------------------------------
# load kext
sh "/Library/Application Support/org.pqrs/Seil/startup.sh" start

# ------------------------------------------------------------
# relaunch Seil.app

/Applications/Seil.app/Contents/Library/bin/seil \
    relaunch

# ------------------------------------------------------------
exit 0
