#!/bin/sh
PATH=/bin:/sbin:/usr/bin:/usr/sbin; export PATH

# ------------------------------------------------------------
# set file permissions
for f in \
    /Applications/Seil.app \
    ; do
    echo "set file permissions: $f"
    sh /Applications/Seil.app/Contents/Library/extra/setpermissions.sh "$f"
    chown -Rh root:wheel "$f"
done

# ------------------------------------------------------------
# relaunch Seil.app

/Applications/Seil.app/Contents/Library/bin/seil \
    relaunch

# ------------------------------------------------------------
exit 0
