#!/bin/sh
# -*- Mode: shell-script -*-

PATH=/bin:/sbin:/usr/bin:/usr/sbin; export PATH

# ----------------------------------------
# unload before install
for f in /Library/LaunchDaemons/org.pqrs.PCKeyboardHack.* /Library/LaunchAgents/org.pqrs.PCKeyboardHack.*; do
    [ -f $f ] && launchctl unload $f 2> /dev/null
done

startup="/Applications/PCKeyboardHack/scripts/startup.sh"
[ -f "$startup" ] && "$startup" stop

startup="/Library/org.pqrs/PCKeyboardHack/scripts/startup.sh"
[ -f "$startup" ] && "$startup" stop

startup="/Applications/PCKeyboardHack.app/Contents/Library/scripts/startup.sh"
[ -f "$startup" ] && "$startup" stop

kextload="/Applications/PCKeyboardHack.app/Contents/Library/bin/kextload"
[ -f "$kextload" ] && "$kextload" unload

kextload="/Applications/Seil.app/Contents/Library/bin/kextload"
[ -f "$kextload" ] && "$kextload" unload

# ----------------------------------------
# uninstall
rm -rf /Applications/Seil.app
rm -rf /Applications/PCKeyboardHack
rm -rf /Applications/PCKeyboardHack.app
rm -rf /Library/org.pqrs/PCKeyboardHack
rmdir /Library/org.pqrs 2>/dev/null

rm -rf /Library/PreferencePanes/PCKeyboardHack.prefPane

rm -f /Library/LaunchDaemons/org.pqrs.PCKeyboardHack.*
rm -f /Library/LaunchAgents/org.pqrs.PCKeyboardHack.*

# Don't remove uninstaller because
# this script is also called from uninstaller and
# we need to keep SeilUninstaller.icns while uninstaller is running.
# rm -rf /tmp/Seil_uninstaller.*

exit 0
